version: '3.1'

services:
  ninty:
    image: ninty:sub
    build:
      context: ..
      dockerfile: script/Dockerfile.dev
    links:
      - db
    ports:
      - 5000:8080
    environment:
      - RDS_HOSTNAME=db
      - RDS_PASSWORD=blah
      - FLASK_ENV=development
    volumes:
      - ../ninty:/var/app/ninty
    entrypoint:
      - bin/python
    command: ["application.py"]