version: '3.1'

services:
  egfds:
    image: egfds:dev
    build:
      context: ..
    links:
      - db
    ports:
      - 5000:8080
    environment:
      - RDS_HOSTNAME=db
      - RDS_PASSWORD=blah
      - FLASK_ENV=development
    volumes:
      - ../egfds:/app/egfds
    entrypoint:
      - python
    command: ["egfds/application.py"]
