version: '3.1'

services:
  egfds:
    image: egfds:dev
    build:
      context: ..
    external_links:
      - egfds-postgres:postgres-dev
    ports:
      - 5000:8080
    environment:
      - RDS_HOSTNAME=postgres-dev
      - FLASK_ENV=development
    volumes:
      - ../egfds:/app/egfds
    entrypoint:
      - python
    command: ["egfds/application.py"]
