version: '3.1'

services:
  egfds:
    image: egfds
    build:
      context: ../build
    ports:
      - 5000:80
    external_links:
      - egfds-postgres:postgres-dev
    environment:
      - RDS_HOSTNAME=postgres-dev
      - STATIC_PATH=/app/egfds/static
      - FLASK_ENV=production