version: '3.1'

services:
  egfds:
    image: egfds
    build:
      context: ../build
    ports:
      - 5000:80
    extra_hosts:
      - postgres-live:${LIVE_IP}
    environment:
      - RDS_HOSTNAME=postgres-live
